#!/bin/bash

# Copyright 2017 Lukas Atkinson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

self="$(basename "$0")"

usage="Usage:
$self [directories] [--] [find-options]
$self --help

A wrapper for the \"find\" command.

Arguments:

    directories
        The directories in which to search.  If none are provided, the current
        directory is searched.

    find-options
        Any filters and actions for the find tool.

Example:

    # list all swapfiles in the lib directory
    $self lib

    # delete all swaptfiles in the current dir
    $self --remove-all
"

dirs=()
remove_all=no

while [[ "$#" -ne 0 ]]
do
    case "$1" in
    -h|--help)
        printf '%s\n' "$usage"
        exit
        ;;
    --remove-all)
        remove_all=yes
        shift
        ;;
    --)
        shift
        break
        ;;
    -*)
        break
        ;;
    *)
        dirs+=("$1")
        shift
        ;;
    esac
done

if [[ "$remove_all" = yes ]]; then
    exec find "${dirs[@]}" -type f -name '.*.sw?' "$@" -exec rm {} +
else
    exec find "${dirs[@]}" -type f -name '.*.sw?' "$@"
fi
