#!/bin/bash

# Copyright 2017 Lukas Atkinson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o pipefail

editor="$EDITOR"
self="$(basename "$0")"

usage="Usage:
    $self [--] [editor [editor_args...]]
    $self --help

Options:

    -h, --help
        Print this message and exit.

Arguments;

    editor
        Open the files with the provided editor. Defaults to the \$EDITOR
        environment variable.
"

while [[ "$#" -ne 0 ]]
do
    case "$1" in
        -h|--help)
            shift
            printf '%s' "$usage"
            exit 0
            ;;
        --)
            shift
            break
            ;;
        -*)
            printf 'Unknown argument: %s\n%s' "$1" "$usage" >&2
            exit 1
            ;;
        *)
            break
            ;;
        esac
done

if [[ "$#" -ne 0 ]]
then
    editor="$1"
    shift
fi

if [[ -z "$editor" ]]
then
    printf 'No editor selected.\n%s' "$usage" >&2
    exit 1
fi

# find all text files that are not gitignored
# xargs -r -- no run if empty
git  ls-files \
         | xargs -r -d '\n' file --mime-type --no-pad \
         | perl -nE'chomp; ($f, $t)=split/: /; say $f if $t =~ m:^text/:' \
         | xargs -d '\n' "$editor" "$@"

